version: "3.6"
services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - replset
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-primary
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  mongo-client:
    image: mongoclient/mongoclient
    restart: always
    ports:
      - 8080:3000
    networks:
      - replset
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter

  mongodb-primary:
    image: mongo:4.2.1-bionic
    container_name: mongodb-primary
    hostname: mongodb-primary
    command: >
      mongod
      --replSet rs0
      --config /etc/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db # Enable persistence of db
      - ./bootstrap:/bootstrap:ro # Initialization scripts
      - ./etc/mongod.conf:/etc/mongod.conf:ro # Permission: 600
      - ./etc/mongod-keyfile:/etc/mongod-keyfile:ro # Permission: 600
    ports:
      - 27017:27017
    networks:
      - replset
    depends_on:
      - mongodb-secondary
      - mongodb-arbiter
    restart: on-failure

  mongodb-secondary:
    image: mongo:4.2.1-bionic
    container_name: mongodb-secondary
    hostname: mongodb-secondary
    command: >
      mongod
      --replSet rs0
      --config /etc/mongod.conf
    volumes:
      - ./etc/mongod.conf:/etc/mongod.conf:ro # Permission: 600
      - ./etc/mongod-keyfile:/etc/mongod-keyfile:ro # Permission: 600
    ports:
      - 27018:27017
    networks:
      - replset
    depends_on:
      - mongodb-arbiter
    restart: on-failure

  mongodb-arbiter:
    image: mongo:4.2.1-bionic
    container_name: mongodb-arbiter
    hostname: mongodb-arbiter
    command: >
      mongod
      --replSet rs0
      --config /etc/mongod.conf
    volumes:
      - ./etc/mongod.conf:/etc/mongod.conf:ro # Permission: 600
      - ./etc/mongod-keyfile:/etc/mongod-keyfile:ro # Permission: 600
    ports:
      - 27019:27017
    networks:
      - replset
    restart: on-failure

networks:
  replset:
    driver: bridge
    name: mongodb

volumes:
  mongodb_data:
    driver: local
